FROM domjudge/judgehost:latest
RUN apt-get update \
		&& apt-get install curl wget gnupg ca-certificates -y
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
		&& echo "deb https://download.mono-project.com/repo/debian stable-stretch main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list \
		&& curl -sL https://deb.nodesource.com/setup_12.x | sudo bash - \
		&& apt-get install nodejs mono-devel -y
CMD ["/scripts/start.sh"]